sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libreadline-dev
            - libssl-dev
            - libzip-dev
            - libglib2.0-dev
      env: MAKEFILE_RULE=manager

    - os: linux
      dist: bionic # Ubuntu 18.04
      group: travis_latest
      name: 'Ubuntu 18.04 Bionic'
      compiler: gcc
      addons:
        apt:
          packages:
            - libreadline-dev
            - libssl-dev
            - libzip-dev
      env: MAKEFILE_RULE=wb

    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libreadline-dev
            - libssl-dev
            - libzip-dev
        coverity_scan:
          project:
            name: "Levak/warfacebot"
            description: "Build submitted via Travis CI"
          notification_email: levak92@gmail.com
          build_command_prepend: "make clean"
          build_command: "make -j 4"
          branch_pattern: master
      env: MAKEFILE_RULE=wb

    - os: linux
      compiler: i686-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - mingw-w64-common
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-base
            - gcc-mingw-w64-i686
            - gcc-mingw-w64
      before_script:
        - wget -O zlib.zip http://zlib.net/zlib128-dll.zip
          && unzip zlib.zip 'zlib1.dll' 'lib/*' 'include/*'
          && mv lib/zdll.lib lib/z.lib
        - wget -O openssl.zip http://downloads.sourceforge.net/gnuwin32/openssl-0.9.8h-1-lib.zip
          && unzip openssl.zip 'lib/*' 'include/*'
        - wget -O readline.zip http://downloads.sourceforge.net/gnuwin32/readline-5.0-1-bin.zip
          && unzip readline.zip 'lib/*' 'include/*' bin/readline5.dll
          && mv bin/readline5.dll readline5.dll
          && rm -vrf bin/
      env: MAKEFILE_RULE=wb OSTYPE=mingw

script:
  - make CC=$CC $MAKEFILE_RULE -j 4

env:
  global:
   # Coverity scan token
   - secure: "WMgpGU/aflZTtgW81JFmdjfR7+vzTIBe0S8+bqf7hBR9SSQgcB3VO+4VoXgEcCr92ZvAvuJCu8KyfF1wIRv+ZjtOOwv3n5qpJvhF4CSemGDySKainJqD3q1/2R7nQxX+dzZiZqsIWNDLsR5eEP81AJ/VPmJRTtPuDQQs5JX1bML+Jf1Rj+/BbmiHVNjUlofkMFMWKoMtEgOf3qPwiCuozL4Qp/ynE03UDO3xwYUWX2KG25nCUR26AAGRJdHhhZb/jXsh2nHEGOuMRRdaEdS9tNBWlV1+gX4O/lUU/GNcm1dRQVtSHC59zYzNSauUQBxlbJI0HiqgRi93cL+f8omx9af7b95Ex/Xbt8o/lMg/9St/QE628F+n9uR1PxukIDXXyiXMvZwuSjES0x9hQTGB42cs957mlkJirWIAkAAPLdqIGdZVz1GKRYn7mWjz6Vhek4nsg5bb5CMf8cJFBUcA3Ao1pGDbO8xp6rL4n6FTuy1TkxLtC0C/7GIiGyUltercTvklFxruL7//XQvGJTAiInvv/1C3X4FCUlGBW3YBQzzVMZCQqZncQx+ohJNxANwdpq0pgfS2Em+bEHW7p6bB+UNuy9pp00tChTwMBzxO6wfukgn2XryIFqTbhbmCvGZyMtOY9j6lJJnlhTTWkwiynEl82VMskezXUgLIVnntfOY="

before_deploy:
  - test -f wb && mv wb wb.exe
    && rm -fv *.zip
    && rm -vrf lib/
    && rm -vrf include/openssl/
    && rm -vrf include/readline/
    && rm -vf include/zlib.h include/zconf.h
    && name="warfacebot-mingw-${TRAVIS_TAG}"
    && for f in *; do mkdir -p "${name}"; cp -r "$f" "${name}"; done
    && find "${name}" -type f -name '*.o' -delete
    && zip -r "${name}.zip" "${name}"

deploy:
  provider: releases
  api_key:
    secure: "i7VSbluZbV4QRgrMxVnYvQL5z4oqoJzriTifkhvPe2I+XH+dQafuAmx96bNcRXh4b+l/2GWyYEEFnaVayohcM8B44XejoR8B4IaKFXQg3VjL8g+qD2JKiLMSzcDXmGjJ6fRCHSVfLJqJW64f5cgwjiGjIG8XIdUOJKe8adhgO2HcNJgXmLbXfOTmQ/jFRO7zUw3BI4Jkx9o6pfJeEap++w391fIEyzI3ygIyInSrvDEk5QNQlrU20PiqO5gb2z7Ro2z6IY9lBGREe+kJC1ZNxybxH2HzMgX3KjTe7j2GoUtWRIRHYNyNXP8Bl0hgLSzGaAcr0d/Tojf5MuU/rlzitLcCPZJ1ELv//cjWO2zarSzOM5sBr9FD2PdXfR9cPTVxb+opMahLcdA/siT2RUnPWb0pHA2PtUCWEFZgd5TpONeh0YwLrcx8HOC2Mou15hJyjU/dwYBO+/FFNfAMM/7Pmkwe6Y8ryzY71ZoQSnwfMQYyHSJ2H7oxIh6uxBmCViEJMHnx3ndHUSclugS3mgpH2i0VbSSdM2qJE6thOR4ynCJ5VHhgOxlwd5S4XjePAJAHTYVzDWC6faO3ZfrSxTz2wldhY02h62GHVg7LRjXLILy/tteQVpNrJwEBFDhz0EQXRiHsZ+OBQaygBFLQ0H/HaJOjs6K8bBfgIrWdfoFfQ9I="
  skip_cleanup: true
  file: warfacebot-mingw-${TRAVIS_TAG}.zip
  on:
    condition: $OSTYPE = mingw
    tags: true
    repo: Levak/warfacebot
